CREATE TABLE EMPLOYEE (
EID INTEGER PRIMARY KEY,
ENAME VARCHAR2(100) NOT NULL,
EDEPARTMENT INTEGER,
EUSERNAME VARCHAR2(20),
EPASSWORD VARCHAR2(20),
REPORTSTO INTEGER,
CONSTRAINT Unique_Username UNIQUE (EUSERNAME),
FOREIGN KEY (REPORTSTO) REFERENCES EMPLOYEE,
FOREIGN KEY (EDEPARTMENT) REFERENCES DEPARTMENT
);

CREATE TABLE FORM (
FID INTEGER PRIMARY KEY,
EID INTEGER,
FDATE DATE,
FTIME TIME,
LOC VARCHAR2(100),
FDESCRIPTION VARCHAR2(100),
FCOST NUMBER,
FORMATID INTEGER,
EVENTID INTEGER,
--Need to include files here somewhere
TIMEMISSED NUMBER,
FOREIGN KEY (FORMATID) REFERENCES GRADEFORMAT,
FOREIGN KEY (EVENTID) REFERENCES EVENTTYPE
);

CREATE TABLE GRADEFORMAT (
FORMATID INTEGER PRIMARY KEY,
FDESCRIPTION VARCHAR2(100),
REQUIREMENT VARCHAR(50)
);

CREATE TABLE EVENTTYPE (
EVENTID INTEGER PRIMARY KEY,
EDESCRIPTION VARCHAR2(100),
COVERAGE INTEGER
);

CREATE TABLE DEPARTMENT (
DEPARTMENTID INTEGER PRIMARY KEY,
DNAME VARCHAR2(50),
HEAD INTEGER,
FOREIGN KEY (HEAD) REFERENCES EMPLOYEE
);