CREATE TABLE EMPLOYEE (
EID INTEGER PRIMARY KEY,
ENAME VARCHAR2(100) NOT NULL,
EDEPARTMENT INTEGER,
EUSERNAME VARCHAR2(20),
EPASSWORD VARCHAR2(20),
REPORTSTO INTEGER,
CONSTRAINT Unique_Username UNIQUE (EUSERNAME),
FOREIGN KEY (REPORTSTO) REFERENCES EMPLOYEE,
FOREIGN KEY (EDEPARTMENT) REFERENCES DEPARTMENT
);

CREATE TABLE REQUEST (
FID INTEGER PRIMARY KEY,
EID INTEGER,
FDATE DATE,
FTIME TIME,
LOC VARCHAR2(100),
FDESCRIPTION VARCHAR2(100),
FCOST NUMBER,
FORMATID INTEGER,
EVENTID INTEGER,
SAPPROVAL INTEGER,
DHAPPROVAL INTEGER,
BCAPPROVAL INTEGER,
STATUS VARCHAR2(10),
--Need to include files here somewhere
TIMEMISSED NUMBER,
FOREIGN KEY (FORMATID) REFERENCES GRADEFORMAT,
FOREIGN KEY (EVENTID) REFERENCES EVENTTYPE
);

CREATE TABLE GRADEFORMAT (
FORMATID INTEGER PRIMARY KEY,
FDESCRIPTION VARCHAR2(100),
REQUIREMENT VARCHAR(50)
);

CREATE TABLE EVENTTYPE (
EVENTID INTEGER PRIMARY KEY,
EDESCRIPTION VARCHAR2(100),
COVERAGE INTEGER
);

CREATE TABLE DEPARTMENT (
DEPARTMENTID INTEGER PRIMARY KEY,
DNAME VARCHAR2(50),
HEAD INTEGER,
FOREIGN KEY (HEAD) REFERENCES EMPLOYEE
);

CREATE SEQUENCE REIM_REQ_IDS
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TR_INSERT_REQUEST
BEFORE INSERT ON REQUEST
FOR EACH ROW
BEGIN
    SELECT REIM_REQ_IDS.NEXTVAL
    INTO :NEW.FID FROM DUAL;
END;